---
##### EXPORTERS #####
- name: Deploy node exporter
  hosts: node_exporter
  become: yes
  roles:
    - node_exporter
  tags: exporter, node

- name: Deploy libvirt exporter
  hosts: libvirt_exporter
  become: yes
  roles:
    - libvirt_exporter
  tags: exporter, libvirt

- name: Deploy podman exporter
  hosts: podman_exporter
  become: yes
  roles:
    - podman_exporter
  tags: exporter, podman

- name: Deploy redfish exporter
  hosts: prometheus
  become: yes
  roles:
    - redfish_exporter
  tags: exporter, redfish

- name: Deploy haproxy exporter
  hosts: haproxy_exporter
  become: yes
  roles:
    - haproxy_exporter
  tags: exporter, haproxy

##### MINIO #####
- name: Deploy minio
  hosts: minio
  become: yes
  roles:
    - minio
  tags: minio

##### THANOS #####
- name: Deploy thanos
  hosts: thanos
  become: yes
  roles:
    - thanos
  tags: thanos

#### PROMETHEUS #####
- name: Deploy prometheus alertmanager
  hosts: alertmanager
  become: yes
  roles:
    - alertmanager
  tags: alertmanager

- name: Deploy prometheus
  hosts: prometheus
  roles:
    - prometheus
  become: yes
  tags: prometheus

#### GRAFANA #####
- name: Deploy grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags: grafana
