---
- name: Gather facts on everything
  hosts: all
  become: yes
  gather_facts: yes

##### EXPORTERS #####
- name: Deploy node exporter
  hosts: "{{ node_exporter_group }}"
  become: yes
  gather_facts: no
  roles:
    - node_exporter
  tags: exporter, node

- name: Deploy libvirt exporter
  hosts: "{{ libvirt_exporter_group }}"
  become: yes
  gather_facts: no
  roles:
    - libvirt_exporter
  tags: exporter, libvirt

- name: Deploy podman exporter
  hosts: "{{ podman_exporter_group }}"
  become: yes
  gather_facts: no
  roles:
    - podman_exporter
  tags: exporter, podman

- name: Deploy redfish exporter
  hosts: "{{ prometheus_group }}"
  become: yes
  gather_facts: no
  roles:
    - redfish_exporter
  tags: exporter, redfish

- name: Deploy haproxy exporter
  hosts: "{{ haproxy_exporter_group }}"
  become: yes
  gather_facts: no
  roles:
    - haproxy_exporter
  tags: exporter, haproxy

##### MINIO #####
- name: Deploy minio
  hosts: "{{ minio_group }}"
  become: yes
  gather_facts: no
  roles:
    - minio
  tags: minio

##### THANOS #####
- name: Deploy thanos
  hosts: "{{ thanos_group }}"
  become: yes
  gather_facts: no
  roles:
    - thanos
  tags: thanos

##### LOKI #####
- name: Deploy loki
  hosts: "{{ loki_group }}"
  become: yes
  gather_facts: no
  roles:
    - loki
  tags: loki

##### PROMTAIL #####
- name: Deploy promtail
  hosts: "{{ promtail_group }}"
  become: yes
  gather_facts: no
  roles:
    - promtail
  tags: promtail

#### PROMETHEUS #####
- name: Deploy prometheus alertmanager
  hosts: "{{ alertmanager_group }}"
  become: yes
  gather_facts: no
  roles:
    - alertmanager
  tags: alertmanager

- name: Deploy prometheus
  hosts: "{{ prometheus_group }}"
  become: yes
  gather_facts: no
  roles:
    - prometheus
  tags: prometheus

#### GRAFANA #####
- name: Deploy grafana
  hosts: "{{ grafana_group }}"
  become: yes
  gather_facts: no
  roles:
    - grafana
  tags: grafana
