---
thanos_container: "quay.io/thanos/thanos:v0.30.1"
thanos_name: "thanos"
compact_http_port: 10902
query_grpc_port: 10903
query_http_port: 10904
store_grpc_port: 10905
store_http_port: 10906
receive_grpc_port: 10907
receive_remote_write_port: 10908
receive_http_port: 10909
thanos_base_path: "/mnt/containers"
thanos_data_path: "{{ thanos_base_path }}/{{ thanos_name }}"
thanos_mount_path: "/data"
