---
- name: Run alertmanager container
  containers.podman.podman_container:
    name: alertmanager
    image: "{{ prometheus_alertmanager_container }}"
    state: started
    ports:
      - "{{ prometheus_alertmanager_port }}:{{ prometheus_alertmanager_port }}"
  tags: alertmanager

