---
- name: Create container log dir
  ansible.builtin.file:
    path: /var/log/containers
    state: directory
    mode: '0755'
  tags: alertmanager

- name: Run alertmanager container
  containers.podman.podman_container:
    name: "{{ prometheus_alertmanager_name }}"
    image: "{{ prometheus_alertmanager_container }}"
    state: started
    ports:
      - "{{ prometheus_alertmanager_port }}:{{ prometheus_alertmanager_port }}"
    log_options: "path=/var/log/containers/{{ prometheus_alertmanager_name }}.json"
    log_driver: k8s-file
  tags: alertmanager

