---
- name: Run node exporter container
  containers.podman.podman_container:
    name: node-exporter
    image: "{{ node_exporter_container }}"
    state: started
    ports:
      - "{{ node_exporter_port }}:{{ node_exporter_port }}"
  tags: exporter

