---
- name: Install podman
  yum: pkg=podman
       state=installed

- name: Create container log dir
  ansible.builtin.file:
    path: /var/log/containers
    state: directory
    mode: '0755'
  tags: exporter

- name: Run node exporter container
  containers.podman.podman_container:
    name: "{{ node_exporter_name }}"
    image: "{{ node_exporter_container }}"
    state: started
    ports:
      - "{{ node_exporter_port }}:{{ node_exporter_port }}"
    log_options: "path=/var/log/containers/{{ node_exporter_name }}.json"
    log_driver: k8s-file
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      names: true
      container_prefix: monitoring
  tags: exporter

- name: enable and start node exporter service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "monitoring-{{ node_exporter_name }}"
  tags: exporter
