---
- name: Create container log dir
  ansible.builtin.file:
    path: /var/log/containers
    state: directory
    mode: '0755'
  tags: exporter

- name: Run node exporter container
  containers.podman.podman_container:
    name: "{{ node_exporter_name }}"
    image: "{{ node_exporter_container }}"
    state: started
    ports:
      - "{{ node_exporter_port }}:{{ node_exporter_port }}"
    log_options: "path=/var/log/containers/{{ node_exporter_name }}.json"
    log_driver: k8s-file
  tags: exporter

