---
- name: Install podman
  yum: pkg=podman
       state=installed

- name: Create container log dir
  ansible.builtin.file:
    path: /var/log/containers
    state: directory
    mode: '0755'
  tags: exporter

- name: Create prometheus config dir
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
  tags: exporter

- name: check if password is defined
  ansible.builtin.fail:
    msg: "Ansible variable redfish_password is not defined, this is required."
  when: redfish_password is undefined

- name: create redfish template file
  template: src=redfish-config.j2 dest=/etc/prometheus/redfish-config.yml
  tags: exporter

- name: Run redfish exporter container
  containers.podman.podman_container:
    name: "{{ redfish_exporter_name }}"
    image: "{{ redfish_exporter_container }}"
    state: started
    command: "/redfish_exporter/redfish-exporter.sh -l /var/log/redfish-exporter.log -d"
    ports:
      - "{{ redfish_exporter_port }}:{{ redfish_exporter_port }}"
    volumes:
      - "/etc/prometheus/redfish-config.yml:/redfish_exporter/config.yml"
    log_options: "path=/var/log/containers/{{ redfish_exporter_name }}.json"
    log_driver: k8s-file
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      names: true
      container_prefix: monitoring
  tags: exporter

- name: enable and start redfish exporter service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "monitoring-{{ redfish_exporter_name }}"
  tags: exporter
