---
- name: Create prometheus config dir
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
  tags: exporter

- name: create redfish template file
  template: src=redfish-config.j2 dest=/etc/prometheus/redfish-config.yml
  tags: exporter

- name: Run redfish exporter container
  containers.podman.podman_container:
    name: redfish-exporter
    image: "{{ redfish_exporter_container }}"
    state: started
    command: "/redfish_exporter/redfish-exporter.sh -l /var/log/redfish-exporter.log -d"
    ports:
      - "{{ redfish_exporter_port }}:{{ redfish_exporter_port }}"
    volumes:
      - "/etc/prometheus/redfish-config.yml:/redfish_exporter/config.yml"
  tags: exporter

