---
- name: Run haproxy exporter container
  containers.podman.podman_container:
    name: haproxy-exporter
    image: "{{ haproxy_exporter_container }}"
    state: started
    # This assumes the scrape uri is http://<ip>/haproxy?stats;csv - change if its not
    command: "--haproxy.scrape-uri=http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/haproxy?stats;csv"                                                                    
    ports:
      - "{{ haproxy_exporter_port }}:{{ haproxy_exporter_port }}"
  tags: exporter, haproxy
   
