---
- name: Install podman
  yum: pkg=podman
       state=installed

- name: Create container log dir
  ansible.builtin.file:
    path: /var/log/containers
    state: directory
    mode: '0755'
  tags: prometheus

- name: Create prometheus config dir
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
  tags: prometheus

- name: Create prometheus alertmanager config dir
  ansible.builtin.file:
    path: /etc/prometheus/alertmanager
    state: directory
    mode: '0755'
  tags: prometheus

- name: create prometheus template file
  template: src=prometheus.j2 dest=/etc/prometheus/prometheus.yml
  tags: prometheus
  notify: Restart Prometheus

- name: copy prometheus alertmanager rules
  ansible.builtin.copy:
    src: files/alertmanager/prometheus-exporter.yml
    dest: /etc/prometheus/alertmanager/prometheus-exporter.yml
    mode: '0644'
  tags: prometheus
  notify: Restart Prometheus

- name: copy node exporter alertmanager rules
  ansible.builtin.copy:
    src: files/alertmanager/node-exporter.yml
    dest: /etc/prometheus/alertmanager/node-exporter.yml
    mode: '0644'
  tags: prometheus
  notify: Restart Prometheus

- name: copy prometheus alertmanager rules
  ansible.builtin.copy:
    src: "files/alertmanager/thanos-{{ item }}.yml"
    dest: "/etc/prometheus/alertmanager/thanos-{{ item }}.yml"
    mode: '0644'
  tags: prometheus
  notify: Restart Prometheus
  with_items:
    - absent
    - compact
    - query
    - receive
    - store

- name: copy loki alertmanager rules
  ansible.builtin.copy:
    src: files/alertmanager/loki.yml
    dest: /etc/prometheus/alertmanager/loki.yml
    mode: '0644'
  tags: prometheus
  notify: Restart Prometheus

- name: copy promtail alertmanager rules
  ansible.builtin.copy:
    src: files/alertmanager/promtail.yml
    dest: /etc/prometheus/alertmanager/promtail.yml
    mode: '0644'
  tags: prometheus
  notify: Restart Prometheus

- name: Run prometheus container
  containers.podman.podman_container:
    name: "{{ prometheus_name }}"
    image: "{{ prometheus_container }}"
    state: started
    ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    volume:
      - "/etc/prometheus:/etc/prometheus"
    log_options: "path=/var/log/containers/{{ prometheus_name }}.json"
    log_driver: k8s-file
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      names: true
      container_prefix: monitoring
  tags: prometheus

- name: enable and start prometheus service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "monitoring-{{ prometheus_name }}"
  tags: prometheus

