---
- name: Create prometheus config dir
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
  tags: prometheus

- name: create prometheus template file
  template: src=prometheus.j2 dest=/etc/prometheus/prometheus.yml
  tags: prometheus
  notify: Restart Prometheus

- name: copy prometheus alertmanager rules
  ansible.builtin.copy:
    src: files/alertmanager/prometheus-exporter.yml
    dest: /etc/prometheus/prometheus-exporter.yml
    mode: '0644'
  tags: prometheus
  notify: Restart Prometheus

- name: copy node exporter alertmanager rules
  ansible.builtin.copy:
    src: files/alertmanager/node-exporter.yml
    dest: /etc/prometheus/node-exporter.yml
    mode: '0644'
  tags: prometheus
  notify: Restart Prometheus

- name: Run prometheus container
  containers.podman.podman_container:
    name: prometheus
    image: "{{ prometheus_container }}"
    state: started
    ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    volume:
      - "/etc/prometheus:/etc/prometheus"
  tags: prometheus
