---
- name: Create container log dir
  ansible.builtin.file:
    path: /var/log/containers
    state: directory
    mode: '0755'
  tags: exporter, haproxy

- name: Install podman
  yum: pkg=podman
       state=installed
  tags: minio

- name: Run minio container
  containers.podman.podman_container:
    name: "{{ minio_name }}"
    image: "{{ minio_container }}"
    state: started
    command: "server {{ minio_path }}"
    env:
      MINIO_ACCESS_KEY: "{{ minio_access_key }}"
      MINIO_SECRET_KEY: "{{ minio_secret_key }}"
    ports:
      - "{{ minio_port }}:{{ minio_port }}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    log_options: "path=/var/log/containers/{{ minio_name }}.json"
    log_driver: k8s-file
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      names: true
      container_prefix: monitoring
  tags: minio

- name: enable and start minio service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "monitoring-{{ minio_name }}"
  tags: minio

- name: wait for minio to be available
  ansible.builtin.wait_for:
    host: "{{ minio_host }}"
    port: "{{ minio_port }}"
    delay: 10
    state: started
  tags: minio

- name: check if we have mc installed
  stat:
    path: "{{ mc_path }}"
  register: mc_stat
  tags: minio

- name: Download mc
  ansible.builtin.get_url:
    url: "{{ mc_url }}"
    dest: "{{ mc_path }}"
    mode: '0755'
  tags: minio
  when: not mc_stat.stat.exists

# Needs boto3 and botocore, maybe via pip?
#- name: Create minio bucket
#  amazon.aws.s3_bucket:
#    name: thanos
#    state: present
#    endpoint_url: http://{{ minio_host }}:{{ minio_port }}
#    access_key: "{{ minio_access_key }}"
#    secret_key: "{{ minio_secret_key }}"

- name: Add minio config
  ansible.builtin.shell: "/usr/local/bin/mc config host add tmp http://{{ minio_host }}:{{ minio_port }} {{ minio_access_key }} {{ minio_secret_key }}"                                               
  tags: minio

# ignore_errors as a first cut effort to skip if it exists
# Should really handle this more elegantly
- name: Create bucket
  ansible.builtin.shell: "/usr/local/bin/mc mb tmp/thanos"
  ignore_errors: yes
  tags: minio

- name: Remove minio config
  ansible.builtin.shell: "/usr/local/bin/mc config host rm tmp"
  tags: minio

